export default {
    LOGIN_USER: 'LOGIN_USER',
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    // RESTORE_USER: 'RESTORE_USER',
    // RESTORE_USER_REQUEST: 'RESTORE_USER_REQUEST',
    // RESTORE_USER_SUCCESS: 'RESTORE_USER_SUCCESS',
    // RESTORE_USER_FAILURE: 'RESTORE_USER_FAILURE',
  
    REGISTER_USER: 'REGISTER_USER',
    REGISTER_USER_REQUEST: 'REGISTER_USER_REQUEST',
    REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
    REGISTER_USER_FAILURE: 'REGISTER_USER_FAILURE',

    GET_ALL_USERS: 'GET_ALL_USERS',
    GET_ALL_USERS_REQUEST:'GET_ALL_USERS_REQUEST',
    GET_ALL_USERS_SUCCESS:'GET_ALL_USERS_SUCCESS',
    GET_ALL_USERS_FAILURE:'GET_ALL_USERS_FAILURE',

    DEBATE_WAITING: 'DEBATE_WAITING',
    DEBATE_WAITING_REQUEST: 'DEBATE_WAITING_REQUEST',
    DEBATE_WAITING_SUCCESS: 'DEBATE_WAITING_SUCCESS',
    DEBATE_WAITING_FAILURE: 'DEBATE_WAITING_FAILURE',

    INVITE_DEBATE:'INVITE_DEBATE',
    INVITE_DEBATE_REQUEST:'INVITE_DEBATE_REQUEST',
    INVITE_DEBATE_SUCCESS:'INVITE_DEBATE_SUCCESS',
    INVITE_DEBATE_FAILURE:'INVITE_DEBATE_FAILURE',

    CANCEL_INVITE:'CANCEL_INVITE',
    CANCEL_INVITE_REQUEST:'CANCEL_INVITE_REQUEST',
    CANCEL_INVITE_SUCCESS:'CANCEL_INVITE_SUCCESS',
    CANCEL_INVITE_FAILURE:'CANCEL_INVITE_FAILURE',

    REJECT_INVITE:'REJECT_INVITE',
    REJECT_INVITE_REQUEST:'REJECT_INVITE_REQUEST',
    REJECT_INVITE_SUCCESS:'REJECT_INVITE_SUCCESS',
    REJECT_INVITE_FAILURE:'REJECT_INVITE_FAILURE',

    ACCEPT_INVITE:'ACCEPT_INVITE',
    ACCEPT_INVITE_REQUEST:'ACCEPT_INVITE_REQUEST',
    ACCEPT_INVITE_SUCCESS:'ACCEPT_INVITE_SUCCESS',
    ACCEPT_INVITE_FAILURE:'ACCEPT_INVITE_FAILURE',

    ACCEPT_WAITING: 'ACCEPT_WAITING',
    ACCEPT_WAITING_REQUEST: 'ACCEPT_WAITING_REQUEST',
    ACCEPT_WAITING_SUCCESS: 'ACCEPT_WAITING_SUCCESS',
    ACCEPT_WAITING_FAILURE: 'ACCEPT_WAITING_FAILURE',

    READY_TOPIC1: "READY_TOPIC1",
    READY_TOPIC1_REQUEST: "READY_TOPIC1_REQUEST",
    READY_TOPIC1_SUCCESS: "READY_TOPIC1_SUCCESS",
    READY_TOPIC1_FAILURE: "READY_TOPIC1_FAILURE",

    CHECK_REDAY1:"CHECK_REDAY1",
    CHECK_REDAY1_REQUEST:"CHECK_REDAY1_REQUEST",
    CHECK_REDAY1_SUCCESS:"CHECK_REDAY1_SUCCESS",
    CHECK_REDAY1_FAILURE:"CHECK_REDAY1_FAILURE",
  };
  